# Compile project on Ubuntu
name: Ubuntu_cpp

on:
  push:
    paths:
      - "!.github/**"
      - ".github/workflows/Ubuntu_cpp.yaml"
      - "cpp/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: ubuntu-20.04
            gcc: 9

          - os: ubuntu-18.04
            gcc: 8

    env:
      cpp_dir: "./cpp"
      build_dir: "./build"
      config: "Release"


    steps:
    - uses: actions/checkout@v2

    # Specify the correct host compilers
    - name: Install/Select gcc and g++ 
      run: |
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
      shell: bash

    - name: Configure cmake
      working-directory: ${{ env.cpp_dir }}
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
      shell: bash

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      working-directory: ${{ env.cpp_dir }}/${{ env.build_dir }}
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi
      shell: bash

    - name: Build everything else
      working-directory: ${{ env.cpp_dir }}
      run: |
       cmake --build ${{ env.build_dir }} --target all --verbose -j `nproc`
      shell: bash

    - name: Run tests
      working-directory: ${{ env.cpp_dir }}
      run: ${{ env.build_dir }}/Google_Tests_run
